apiVersion: v1
kind: Service
metadata:
  name: villa-service
spec:
  selector:
    app: villa-frontend # Change this selector to match your deployment's label
  ports:
    - protocol: TCP
      port: 80        # The port on the service
      targetPort: 80     # The port the app is listening to inside the pod
      nodePort: 32000      # This is the external port on which the service will be accessible
  type: NodePort
