apiVersion: apps/v1
kind: Deployment
metadata:
  name: villa-frontend
  labels:
    app: villa-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: villa-frontend
  template:
    metadata:
      labels:
        app: villa-frontend
    spec:
      containers:
      - name: villa-frontend-container
        image: 491085423090.dkr.ecr.ap-south-1.amazonaws.com/docker_rlogical:20250814-1330
        imagePullPolicy: Always
        ports:
        - containerPort: 80
