name: Deploy to Amazon ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: docker_rlogical

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set timestamp for image tag
      id: timestamp
      run: |
        echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker_rlogical
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        echo "Building Docker image with tag: $IMAGE_TAG"
        IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY
        docker build -t $IMAGE_URI:$IMAGE_TAG .
        docker tag $IMAGE_URI:$IMAGE_TAG $IMAGE_URI:latest
        docker push $IMAGE_URI:$IMAGE_TAG
        docker push $IMAGE_URI:latest

    # Update K8s manifest
    - name: Update K8s Manifests
      run: |
        sed -i "s|image: 491085423090.dkr.ecr.ap-south-1.amazonaws.com/docker_rlogical:.*|image: 491085423090.dkr.ecr.ap-south-1.amazonaws.com/docker_rlogical:${{ env.IMAGE_TAG }}|" deployment/depoy.yml
        cat deployment/deploy.yml

    # Commit the changes to GitHub
    - name: Commit the changes
      run: |
        git config --global user.email "<karanravat60@gmail.com>"
        git config --global user.name "Karan Ravat"
        git add deployment/deploy.yaml
        git commit -m "Update deploy.yaml with new image version - ${{ env.IMAGE_TAG }}"
        git remote set-url origin https://github.com/callmekaran/Docker_html_Rlogical.git
        git push origin main

